packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/engines': true
  '@reown/appkit': true
  esbuild: true
  msgpackr-extract: false
  prisma: true
  unrs-resolver: true
  workerd: false

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma

overrides:
  lodash: 4.18.1
  deepmerge-ts: 8.0.0
  mysql2: 3.22.0
