'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { Check, ChevronLeft, ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { calculateJoinAllocation, formatNumber } from '@/lib/finance';

const steps = ['Amount', 'Inviter', 'Review', 'Confirm'] as const;
const allocationTone = ['var(--red)', 'var(--cyan)', 'var(--blue)'] as const;

export function JoinFlow() {
  const [step, setStep] = useState(0); const [amount, setAmount] = useState('10000'); const [inviter, setInviter] = useState(''); const [processing, setProcessing] = useState(false); const [complete, setComplete] = useState(false);
  const allocation = useMemo(() => { try { return calculateJoinAllocation(amount); } catch { return calculateJoinAllocation(0); } }, [amount]);
  const confirm = () => { setProcessing(true); window.setTimeout(() => { setProcessing(false); setComplete(true); }, 1400); };
  if (complete) return <div className="glass mx-auto max-w-xl rounded-2xl p-8 text-center"><span className="mx-auto grid size-14 place-items-center rounded-full bg-[var(--success)]/10 text-[var(--success)]"><Check /></span><p className="eyebrow mt-8">DEMO CONFIRMATION</p><h2 className="mt-3 text-3xl font-light">XGOU AGENT STARTED</h2><p className="mt-4 text-sm text-white/45">没有调用合约，也没有移动任何资金。</p><Button asChild className="mt-8"><Link href="/dashboard">进入总览</Link></Button></div>;
  return <div className="mx-auto max-w-3xl"><div className="mb-7 grid grid-cols-4 gap-2">{steps.map((label, index) => <div key={label} className={index <= step ? 'text-white' : 'text-white/25'}><div className={`h-px ${index <= step ? 'bg-white/70' : 'bg-white/10'}`} /><p className="mt-2 text-[9px] tracking-[.12em]">STEP {String(index + 1).padStart(2, '0')}</p><p className="mt-1 text-[10px]">{label}</p></div>)}</div><div className="glass rounded-2xl p-6 md:p-9"><div className="flex items-center justify-between"><p className="eyebrow">STEP {String(step + 1).padStart(2, '0')} · {steps[step]}</p><span className="text-[9px] text-white/30">DEMO ONLY</span></div>
    {step === 0 && <div className="mt-9"><label className="text-xs text-white/45">参与金额</label><div className="mt-3 flex items-center rounded-xl bg-white/[.025] px-5 py-4 ring-1 ring-white/[.08] focus-within:ring-white/20"><input aria-label="Participation Amount" value={amount} onChange={(event) => { setAmount(event.target.value.replace(/[^0-9.]/g, '')); }} className="min-w-0 flex-1 bg-transparent text-4xl font-light outline-none md:text-6xl" /><span className="text-sm text-white/40">USDC</span></div><div className="mt-7 grid gap-3 sm:grid-cols-3">{[['BULL FUND','50%',allocation.bull],['SPOT AGENT','30%',allocation.spot],['FUTURES TREND','20%',allocation.futures]].map(([name, share, value], index) => <div key={String(name)} className="rounded-xl bg-white/[.02] p-4 ring-1 ring-white/[.06]" style={{ boxShadow: `inset 2px 0 ${allocationTone[index] ?? 'white'}` }}><div className="flex justify-between text-[9px] tracking-wider text-white/40"><span>{String(name)}</span><span style={{ color: allocationTone[index] }}>{String(share)}</span></div><p className="mt-4 text-xl">{formatNumber(String(value), 8)}</p></div>)}</div></div>}
    {step === 1 && <div className="mt-9"><label className="text-xs text-white/45">邀请人钱包 · Demo 可选</label><input aria-label="Inviter Wallet" value={inviter} onChange={(event) => { setInviter(event.target.value); }} placeholder="0x…" className="mt-3 h-14 w-full rounded-xl border border-white/[.08] bg-black/20 px-4 outline-none focus:border-[var(--cyan)]" /><div className="mt-5 rounded-xl bg-white/[.025] p-4 text-xs text-white/40">{inviter ? 'INVITER BOUND · DEMO VALIDATION' : '预览环境可不填写邀请人。'}</div></div>}
    {step === 2 && <div className="mt-8 rounded-xl border border-white/[.07] p-5"><div className="flex justify-between"><span className="eyebrow">TOTAL</span><strong>{formatNumber(allocation.total.toFixed())} USDC</strong></div>{[['BULL · 50%',allocation.bull],['SPOT · 30%',allocation.spot],['FUTURES · 20%',allocation.futures],['PRINCIPAL XP',allocation.principalXp]].map(([label, value]) => <div key={String(label)} className="mt-4 flex justify-between border-t border-white/[.05] pt-4 text-sm"><span className="text-white/40">{String(label)}</span><span>{formatNumber(String(value))}{String(label) === 'PRINCIPAL XP' ? ' XP' : ' USDC'}</span></div>)}</div>}
    {step === 3 && <div className="mt-9 rounded-xl bg-white/[.025] p-6 text-center"><p className="text-2xl font-light">确认 Demo 配置</p><p className="mt-3 text-sm leading-6 text-white/45">不会触发 Approve、Deposit、钱包签名或任何合约调用。</p><p className="mt-5 font-mono text-sm">{formatNumber(allocation.total.toFixed())} USDC · {formatNumber(allocation.principalXp.toFixed())} XP</p></div>}
    <div className="mt-9 flex justify-between"><Button variant="outline" disabled={step === 0 || processing} onClick={() => { setStep((current) => current - 1); }}><ChevronLeft size={14} />返回</Button>{step < 3 ? <Button disabled={allocation.total.lte(0)} onClick={() => { setStep((current) => current + 1); }}>继续<ChevronRight size={14} /></Button> : <Button disabled={processing} onClick={confirm}>{processing ? '处理中…' : 'CONFIRM DEMO'}</Button>}</div>
  </div></div>;
}
