ALTER TABLE "StrategyAccount"
ADD COLUMN "dailyOpeningNav" DECIMAL(36,18) NOT NULL DEFAULT 0,
ADD COLUMN "dailyPnlRatio" DECIMAL(36,18) NOT NULL DEFAULT 0,
ADD COLUMN "dailyBaselineAt" TIMESTAMP(3),
ADD COLUMN "weeklyPnl" DECIMAL(36,18) NOT NULL DEFAULT 0,
ADD COLUMN "weeklyOpeningNav" DECIMAL(36,18) NOT NULL DEFAULT 0,
ADD COLUMN "weeklyPnlRatio" DECIMAL(36,18) NOT NULL DEFAULT 0,
ADD COLUMN "weeklyBaselineAt" TIMESTAMP(3);

ALTER TABLE "Position"
ADD COLUMN "stopLoss" DECIMAL(36,18),
ADD COLUMN "takeProfit" DECIMAL(36,18),
ADD COLUMN "trailingStop" DECIMAL(36,18),
ADD COLUMN "markedAt" TIMESTAMP(3);
