CREATE TABLE "SandboxTransportControl" (
  "id" VARCHAR(64) PRIMARY KEY,
  "exchange" VARCHAR(32) NOT NULL,
  "environment" "ProductionEnvironment" NOT NULL DEFAULT 'TESTNET',
  "enabled" BOOLEAN NOT NULL DEFAULT false,
  "approvalRequestId" UUID,
  "enabledBy" VARCHAR(128),
  "enabledAt" TIMESTAMP(3),
  "disabledReason" VARCHAR(512),
  "version" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX "SandboxTransportControl_exchange_environment_key" ON "SandboxTransportControl"("exchange", "environment");

CREATE TABLE "SandboxStrategyAccount" ("id" UUID PRIMARY KEY, "strategyCode" VARCHAR(64) NOT NULL, "exchange" VARCHAR(32) NOT NULL, "accountType" VARCHAR(16) NOT NULL, "credentialProfileId" UUID NOT NULL, "quoteAsset" VARCHAR(16) NOT NULL, "status" VARCHAR(32) NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "SandboxStrategyAccount_strategyCode_exchange_accountType_key" ON "SandboxStrategyAccount"("strategyCode", "exchange", "accountType");
CREATE INDEX "SandboxStrategyAccount_credentialProfileId_status_idx" ON "SandboxStrategyAccount"("credentialProfileId", "status");

CREATE TABLE "SandboxOrder" ("id" UUID PRIMARY KEY, "proposalId" UUID NOT NULL, "riskDecisionId" UUID NOT NULL, "authorizationId" UUID NOT NULL, "strategyAccountId" UUID, "internalClientOrderId" VARCHAR(128) NOT NULL, "exchangeClientOrderId" VARCHAR(36) NOT NULL, "exchangeOrderId" VARCHAR(128), "exchange" VARCHAR(32) NOT NULL DEFAULT 'BINANCE', "environment" "ProductionEnvironment" NOT NULL DEFAULT 'TESTNET', "accountType" VARCHAR(16) NOT NULL, "symbol" VARCHAR(32) NOT NULL, "side" VARCHAR(16) NOT NULL, "type" VARCHAR(32) NOT NULL, "quantity" DECIMAL(36,18) NOT NULL, "quoteQuantity" DECIMAL(36,18), "price" DECIMAL(36,18), "stopPrice" DECIMAL(36,18), "reduceOnly" BOOLEAN NOT NULL DEFAULT false, "leverage" INTEGER, "state" "ExecutionState" NOT NULL DEFAULT 'AUTHORIZED', "networkSent" BOOLEAN NOT NULL DEFAULT false, "unknownReason" VARCHAR(512), "recoveryCount" INTEGER NOT NULL DEFAULT 0, "lastQueriedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "SandboxOrder_internalClientOrderId_key" ON "SandboxOrder"("internalClientOrderId"); CREATE UNIQUE INDEX "SandboxOrder_exchangeClientOrderId_key" ON "SandboxOrder"("exchangeClientOrderId"); CREATE INDEX "SandboxOrder_state_createdAt_idx" ON "SandboxOrder"("state", "createdAt"); CREATE INDEX "SandboxOrder_proposalId_riskDecisionId_authorizationId_idx" ON "SandboxOrder"("proposalId", "riskDecisionId", "authorizationId"); CREATE INDEX "SandboxOrder_exchangeOrderId_idx" ON "SandboxOrder"("exchangeOrderId");

CREATE TABLE "SandboxExecutionLedger" ("id" UUID PRIMARY KEY, "orderId" UUID NOT NULL, "eventType" VARCHAR(64) NOT NULL, "stateBefore" VARCHAR(32), "stateAfter" VARCHAR(32) NOT NULL, "details" JSONB NOT NULL, "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "SandboxExecutionLedger_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "SandboxOrder"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE UNIQUE INDEX "SandboxExecutionLedger_orderId_eventType_occurredAt_key" ON "SandboxExecutionLedger"("orderId", "eventType", "occurredAt"); CREATE INDEX "SandboxExecutionLedger_orderId_occurredAt_idx" ON "SandboxExecutionLedger"("orderId", "occurredAt");
CREATE TABLE "SandboxFill" ("id" UUID PRIMARY KEY, "orderId" UUID NOT NULL, "exchangeTradeId" VARCHAR(128) NOT NULL, "quantity" DECIMAL(36,18) NOT NULL, "price" DECIMAL(36,18) NOT NULL, "quoteQuantity" DECIMAL(36,18) NOT NULL, "commission" DECIMAL(36,18) NOT NULL, "commissionAsset" VARCHAR(16) NOT NULL, "executedAt" TIMESTAMP(3) NOT NULL, "raw" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "SandboxFill_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "SandboxOrder"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE UNIQUE INDEX "SandboxFill_orderId_exchangeTradeId_key" ON "SandboxFill"("orderId", "exchangeTradeId"); CREATE INDEX "SandboxFill_executedAt_idx" ON "SandboxFill"("executedAt");

CREATE TABLE "SandboxSpotPosition" ("id" UUID PRIMARY KEY, "strategyAccountId" UUID NOT NULL, "symbol" VARCHAR(32) NOT NULL, "quantity" DECIMAL(36,18) NOT NULL, "averagePrice" DECIMAL(36,18) NOT NULL, "realizedPnl" DECIMAL(36,18) NOT NULL DEFAULT 0, "updatedAt" TIMESTAMP(3) NOT NULL); CREATE UNIQUE INDEX "SandboxSpotPosition_strategyAccountId_symbol_key" ON "SandboxSpotPosition"("strategyAccountId", "symbol");
CREATE TABLE "SandboxFuturesPosition" ("id" UUID PRIMARY KEY, "strategyAccountId" UUID NOT NULL, "symbol" VARCHAR(32) NOT NULL, "positionSide" VARCHAR(16) NOT NULL DEFAULT 'BOTH', "quantity" DECIMAL(36,18) NOT NULL, "entryPrice" DECIMAL(36,18) NOT NULL, "markPrice" DECIMAL(36,18) NOT NULL, "leverage" INTEGER NOT NULL, "marginType" VARCHAR(16) NOT NULL, "unrealizedPnl" DECIMAL(36,18) NOT NULL DEFAULT 0, "liquidationPrice" DECIMAL(36,18), "updatedAt" TIMESTAMP(3) NOT NULL); CREATE UNIQUE INDEX "SandboxFuturesPosition_strategyAccountId_symbol_positionSide_key" ON "SandboxFuturesPosition"("strategyAccountId", "symbol", "positionSide");
CREATE TABLE "ProtectiveOrder" ("id" UUID PRIMARY KEY, "orderId" UUID NOT NULL, "exchangeClientOrderId" VARCHAR(36) NOT NULL, "exchangeOrderId" VARCHAR(128), "type" VARCHAR(32) NOT NULL, "stopPrice" DECIMAL(36,18) NOT NULL, "reduceOnly" BOOLEAN NOT NULL DEFAULT true, "state" "ExecutionState" NOT NULL DEFAULT 'AUTHORIZED', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ProtectiveOrder_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "SandboxOrder"("id") ON DELETE RESTRICT ON UPDATE CASCADE); CREATE UNIQUE INDEX "ProtectiveOrder_exchangeClientOrderId_key" ON "ProtectiveOrder"("exchangeClientOrderId"); CREATE INDEX "ProtectiveOrder_orderId_state_idx" ON "ProtectiveOrder"("orderId", "state");
CREATE TABLE "SandboxFundingRecord" ("id" UUID PRIMARY KEY, "strategyAccountId" UUID NOT NULL, "exchangeIncomeId" VARCHAR(128) NOT NULL, "symbol" VARCHAR(32), "incomeType" VARCHAR(32) NOT NULL, "asset" VARCHAR(16) NOT NULL, "amount" DECIMAL(36,18) NOT NULL, "occurredAt" TIMESTAMP(3) NOT NULL, "raw" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE UNIQUE INDEX "SandboxFundingRecord_exchangeIncomeId_key" ON "SandboxFundingRecord"("exchangeIncomeId"); CREATE INDEX "SandboxFundingRecord_strategyAccountId_occurredAt_idx" ON "SandboxFundingRecord"("strategyAccountId", "occurredAt");
CREATE TABLE "ExchangeAccountSnapshot" ("id" UUID PRIMARY KEY, "strategyAccountId" UUID NOT NULL, "exchange" VARCHAR(32) NOT NULL, "accountType" VARCHAR(16) NOT NULL, "balances" JSONB NOT NULL, "capturedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE INDEX "ExchangeAccountSnapshot_strategyAccountId_capturedAt_idx" ON "ExchangeAccountSnapshot"("strategyAccountId", "capturedAt");
CREATE TABLE "ExchangePositionSnapshot" ("id" UUID PRIMARY KEY, "strategyAccountId" UUID NOT NULL, "positions" JSONB NOT NULL, "capturedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE INDEX "ExchangePositionSnapshot_strategyAccountId_capturedAt_idx" ON "ExchangePositionSnapshot"("strategyAccountId", "capturedAt");
CREATE TABLE "ExchangeOrderSnapshot" ("id" UUID PRIMARY KEY, "strategyAccountId" UUID NOT NULL, "orders" JSONB NOT NULL, "capturedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE INDEX "ExchangeOrderSnapshot_strategyAccountId_capturedAt_idx" ON "ExchangeOrderSnapshot"("strategyAccountId", "capturedAt");
CREATE TABLE "SandboxReconciliationRun" ("id" UUID PRIMARY KEY, "exchange" VARCHAR(32) NOT NULL DEFAULT 'BINANCE', "accountType" VARCHAR(16) NOT NULL, "status" "ReconciliationRunStatus" NOT NULL DEFAULT 'RUNNING', "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "finishedAt" TIMESTAMP(3), "criticalCount" INTEGER NOT NULL DEFAULT 0, "error" VARCHAR(1024)); CREATE INDEX "SandboxReconciliationRun_status_startedAt_idx" ON "SandboxReconciliationRun"("status", "startedAt");
CREATE TABLE "SandboxReconciliationDifference" ("id" UUID PRIMARY KEY, "runId" UUID NOT NULL, "category" VARCHAR(32) NOT NULL, "referenceId" VARCHAR(128) NOT NULL, "internal" JSONB NOT NULL, "external" JSONB NOT NULL, "severity" "ReconciliationSeverity" NOT NULL, "status" "ReconciliationStatus" NOT NULL DEFAULT 'OPEN', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "SandboxReconciliationDifference_runId_fkey" FOREIGN KEY ("runId") REFERENCES "SandboxReconciliationRun"("id") ON DELETE RESTRICT ON UPDATE CASCADE); CREATE INDEX "SandboxReconciliationDifference_runId_severity_idx" ON "SandboxReconciliationDifference"("runId", "severity");
CREATE TABLE "SandboxRecoveryCursor" ("id" VARCHAR(64) PRIMARY KEY, "exchange" VARCHAR(32) NOT NULL, "accountType" VARCHAR(16) NOT NULL, "lastTradeTime" TIMESTAMP(3), "lastIncomeTime" TIMESTAMP(3), "lastOrderTime" TIMESTAMP(3), "updatedAt" TIMESTAMP(3) NOT NULL); CREATE UNIQUE INDEX "SandboxRecoveryCursor_exchange_accountType_key" ON "SandboxRecoveryCursor"("exchange", "accountType");
