import { createHash } from 'node:crypto';

export interface BinanceClientOrderAssociation {
  readonly strategy: string;
  readonly cycle: string;
  readonly proposalId: string;
}

const segment = (value: string, limit: number): string => value.toLowerCase().replace(/[^a-z0-9_-]/g, '').slice(0, limit) || 'x';

export class BinanceClientOrderIdCodec {
  encode(input: BinanceClientOrderAssociation): string {
    const hash = createHash('sha256').update(`${input.strategy}\0${input.cycle}\0${input.proposalId}`).digest('hex').slice(0, 16);
    const id = `xg-${segment(input.strategy, 6)}-${segment(input.cycle, 6)}-${hash}`;
    if (id.length > 36 || !/^[.A-Z:/a-z0-9_-]{1,36}$/.test(id)) throw new Error('invalid Binance client order id');
    return id;
  }

  decodeHint(clientOrderId: string): { readonly strategyHint: string; readonly cycleHint: string; readonly associationHash: string } {
    const match = /^xg-([a-z0-9_-]+)-([a-z0-9_-]+)-([a-f0-9]{16})$/.exec(clientOrderId);
    if (!match) throw new Error('client order id was not generated by XGOU');
    const [, strategyHint, cycleHint, associationHash] = match;
    if (!strategyHint || !cycleHint || !associationHash) throw new Error('invalid XGOU client order id');
    return { strategyHint, cycleHint, associationHash };
  }
}
