import { AgentStatus } from '@/components/agent/AgentStatus';
import { PositionTable } from '@/components/agent/PositionTable';
import { StrategyCard } from '@/components/agent/StrategyCard';
import { NavChart } from '@/components/charts/NavChart';
import { PageHeader } from '@/components/layout/PageHeader';
import { formatNumber, formatUsd } from '@/lib/finance';
import { getXgouDataProvider } from '@/services/xgou-data-provider';

export default async function AgentPage() {
  const agent = await getXgouDataProvider().getAgentFund();
  return <><PageHeader eyebrow="SPOT ENGINE · PAPER" title="Autonomous strategy control room" description="现货策略仅执行 Paper Trading；所有提案先经过独立 Risk Engine，不会发送真实订单。" /><div className="mb-4 flex flex-wrap gap-2"><span className="rounded-full border border-cyan-400/40 bg-cyan-400/10 px-3 py-1 text-xs text-cyan-300">PAPER TRADING</span><span className="rounded-full border border-white/15 px-3 py-1 text-xs">{agent.status}</span><span className="rounded-full border border-white/15 px-3 py-1 text-xs">RISK · {agent.circuitState}</span></div><div className="grid gap-4 xl:grid-cols-2"><StrategyCard name="SPOT SWING V1 · PAPER" allocation="30%" tone="cyan" metrics={[{ label: 'NAV', value: formatUsd(agent.spot.nav) }, { label: 'REALIZED PNL', value: formatUsd(agent.realizedPnl) }, { label: 'UNREALIZED PNL', value: formatUsd(agent.unrealizedPnl) }, { label: 'CASH RESERVE', value: formatUsd(agent.reserveBalance) }, { label: 'EXPOSURE', value: `${formatNumber(agent.spot.exposure)}%` }, { label: 'RISK', value: agent.spot.risk }]} /><StrategyCard name="FUTURES TREND · NOT ACTIVE YET" allocation="20%" tone="blue" metrics={[{ label: 'STATUS', value: 'NOT ACTIVE YET' }, { label: 'REAL EXECUTION', value: 'DISABLED' }, { label: 'LEVERAGE', value: 'N/A' }, { label: 'MARGIN USAGE', value: 'N/A' }, { label: 'DRAWDOWN', value: 'N/A' }, { label: 'RISK', value: 'INACTIVE' }]} /></div><div className="mt-4 grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><PositionTable positions={agent.positions} /><div className="glass rounded-2xl p-6"><p className="eyebrow">AGENT STATUS</p><div className="mt-4"><AgentStatus name="Research Agent" status="ONLINE" detail="BTC / ETH / SOL 公开行情与指标" /><AgentStatus name="Spot Agent" status="PAPER" detail={`${formatNumber(agent.spot.exposure)}% 当前虚拟敞口`} /><AgentStatus name="Futures Trend" status="INACTIVE" detail="Phase 3A 不启用" /><AgentStatus name="Risk Engine" status={agent.circuitState} detail="每个 Paper 执行提案均经过风控门控" /></div></div></div><div className="mt-4 grid gap-4 xl:grid-cols-2"><NavChart data={agent.pnlHistory} title="SPOT NAV · PAPER" color="var(--cyan)" /><div className="glass rounded-2xl p-6"><p className="eyebrow">RECENT PAPER TRADES</p><div className="mt-4 space-y-3">{agent.recentTrades.map((trade) => <div key={trade.id} className="flex items-center justify-between border-b border-white/10 pb-3 text-sm"><span><b className="text-cyan-300">PAPER</b> · {trade.side} {trade.symbol}</span><span className="text-white/60">{trade.quantity} @ {trade.price}</span></div>)}</div></div></div></>;
}
